opt:
  _target_: robotmdar.torch.optim.Adam
  lr: ${..manager.learning_rate}

manager:
  _target_: robotmdar.train.manager.DARManager
  stages:
    - 50000
    - 50000
    - 50000
    - 150000

  use_rollout: False     # True
  use_static_pose: False   # True 

  static_prob: 0.001
  static_perturbation_scale: 0.0

  # Full DDPM sampling settings
  use_full_sample: False   # True

  save_every: 20000
  eval_every: 2000
  eval_steps: 10

  device: ${...device}
  save_dir: ${...experiment_dir}

  learning_rate: 0.0001
  anneal_lr: True
  max_grad_norm: 1.0

  # EMA settings
  use_ema: False
  ema_decay: 0.999

  loss_weight:
    rec: 1.0
    kl: 1e-4
    latent_rec: 1.0
    body_trans: 0.05
    body_rot: 1e-2
    dof_pos: 0.03
    dof_vel: 1e-5
    foot_contact: 0.01

    fk_joints_rec: 1.0
    joints_consistency: 1.0
    joints_delta: 1.0
    trans_delta: 1.0
    orient_delta: 1.0

    dof_delta: 1.0
    smooth: 0.0

    quantize_rot: 0.0
    quantize_trans: 0.0
    
    drift_yaw: 0.0
    drift_xy: 0.0

  ckpt: ${...ckpt}

  platform:
    _target_: robotmdar.train.train_platforms.TensorboardPlatform
    save_dir: ${..save_dir}

