_target_: robotmdar.model.mld_vae.AutoMldVae
nfeats: ${..nfeats}
latent_dim: [ 1, 128 ]
h_dim: 512    # 512
ff_size: 1024     # 1024
num_layers: 9
num_heads: 4
dropout: 0.1
arch: all_encoder
normalize_before: false
activation: gelu
position_embedding: learned
