_target_: robotmdar.model.mld_denoiser.DenoiserTransformer
h_dim: 512
ff_size: 1024
num_layers: 8
num_heads: 4
dropout: 0.1
activation: gelu
clip_dim: 512
history_shape:
  - 2
  - ${...nfeats}
noise_shape: [ 1, 128 ]
cond_mask_prob: 0.1
